services:
  backend:
    build: ./
    restart: always
    networks:
      - app-network
  
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
